name: Run Maven Tests on Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Maven Tests
        working-directory: server/web-server
        run: mvn test

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: server/web-server/target/surefire-reports/
